package by.vfedorenko.wishlist.android.presentation.compose.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF2563EB)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFC5CAE9)
val md_theme_light_onPrimaryContainer = Color(0xFF280057)
val md_theme_light_secondary = Color(0x993C3C43)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFECDCFF)
val md_theme_light_onSecondaryContainer = Color(0xFF280057)
val md_theme_light_tertiary = Color(0xFF6F4DA0)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC5CAE9)
val md_theme_light_onTertiaryContainer = Color(0xFF280056)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF2F2F7)
val md_theme_light_onBackground = Color(0xFF1D1B1E)
val md_theme_light_outline = Color(0xFF7B757F)
val md_theme_light_inverseOnSurface = Color(0xFFF5EFF4)
val md_theme_light_inverseSurface = Color(0xFF323033)
val md_theme_light_inversePrimary = Color(0xFFD6BAFF)
val md_theme_light_surfaceTint = Color(0xFFEDE7F6)
val md_theme_light_outlineVariant = Color(0xFFCCC4CF)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1D1B1E)
val md_theme_light_surfaceVariant = Color(0xFFE8E0EB)
val md_theme_light_onSurfaceVariant = Color(0xFF4A454E)

val md_theme_dark_primary = Color(0xFFD6BAFF)
val md_theme_dark_onPrimary = Color(0xFF420089)
val md_theme_dark_primaryContainer = Color(0xFF5F00C0)
val md_theme_dark_onPrimaryContainer = Color(0xFFECDCFF)
val md_theme_dark_secondary = Color(0xFFD6BAFF)
val md_theme_dark_onSecondary = Color(0xFF3E1C6F)
val md_theme_dark_secondaryContainer = Color(0xFF553587)
val md_theme_dark_onSecondaryContainer = Color(0xFFECDCFF)
val md_theme_dark_tertiary = Color(0xFFD7BAFF)
val md_theme_dark_onTertiary = Color(0xFF3F1C6E)
val md_theme_dark_tertiaryContainer = Color(0xFF563587)
val md_theme_dark_onTertiaryContainer = Color(0xFFEDDCFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1D1B1E)
val md_theme_dark_onBackground = Color(0xFFE6E1E6)
val md_theme_dark_outline = Color(0xFF958E99)
val md_theme_dark_inverseOnSurface = Color(0xFF1D1B1E)
val md_theme_dark_inverseSurface = Color(0xFFE6E1E6)
val md_theme_dark_inversePrimary = Color(0xFF7D03F8)
val md_theme_dark_surfaceTint = Color(0xFFD6BAFF)
val md_theme_dark_outlineVariant = Color(0xFF4A454E)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_surface = Color(0xFF141316)
val md_theme_dark_onSurface = Color(0xFFCAC5CA)
val md_theme_dark_surfaceVariant = Color(0xFF4A454E)
val md_theme_dark_onSurfaceVariant = Color(0xFFCCC4CF)

val seed = Color(0xFF7D01F8)

val purple = Color(0xFF9A6ABC)
